apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wiseman-v2-heimdall-bridge
  namespace: midgard-apps
spec:
  podSelector:
    matchLabels:
      app: wiseman-v2-gateway
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: heimdall
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: heimdall
      ports:
        - protocol: TCP
          port: 9300
